#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("AndToasty.Resource", IsApplication=false)]

namespace AndToasty
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int ic_check_white_48dp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int ic_clear_white_48dp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int ic_error_outline_white_48dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int ic_info_outline_white_48dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int ic_warning_outline_white = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int ic_warning_white_48dp = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int toast_frame = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public static int ToastIcon = 2131034113;
			
			// aapt resource value: 0x7f050000
			public static int ToastRoot = 2131034112;
			
			// aapt resource value: 0x7f050002
			public static int ToastText = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int ToastLayout = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public static int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
